version: '3.4'

services:
  samba:
    image: dperson/samba
    env_file: .env

    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /mnt/raid/samba:/samba:z
      - /mnt/raid/plex:/samba/plex:z
    
    # command: '-s "test_share;/mnt" -u "test;test"'

networks:
  default:

